#!/usr/bin/env python3
"""Create exactly one unittest file for each confirmed API inventory entry."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


GENERATED_MARKER = "# Generated by scripts/generate_endpoint_tests.py; do not merge API files."
ROUTE_TEST_POINTS = {
    "ACTIVE": "TP-COMPATIBILITY-API-CONTRACT-001",
    "ROUTE_ONLY": "TP-COMPATIBILITY-API-CONTRACT-002",
    "NAMESPACE_MISMATCH": "TP-COMPATIBILITY-API-CONTRACT-003",
}
BODY_METHODS = {"POST", "PATCH", "PUT"}


def slug(endpoint: dict) -> str:
    path = endpoint["path"].strip("/")
    path = re.sub(r":([A-Za-z_][A-Za-z0-9_]*)", r"by_\1", path)
    path = re.sub(r"[^A-Za-z0-9]+", "_", path).strip("_").lower()
    return f"test_{endpoint['id'].lower().replace('-', '_')}_{endpoint['method'].lower()}_{path}.py"


def class_name(endpoint_id: str) -> str:
    return "Test" + endpoint_id.replace("-", "")


def render(endpoint: dict, fixture_config: dict) -> str:
    purpose = endpoint["purpose"].replace('"""', '\"\"\"')
    test_point = ROUTE_TEST_POINTS[endpoint["wiring"]]
    override = fixture_config.get("cases", {}).get(endpoint["id"], {})
    data_declaration = ""
    data_argument = ""
    if endpoint["method"] in BODY_METHODS:
        if "body" not in override:
            raise ValueError(
                f"{endpoint['id']} {endpoint['method']} endpoint requires an explicit body fixture"
            )
        data_declaration = f"        data = {override['body']!r}\n\n"
        data_argument = "            json_body=data,\n"
    return f'''{GENERATED_MARKER}
"""{endpoint['id']} {endpoint['method']} {endpoint['source_path']} — {purpose}."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class {class_name(endpoint['id'])}(EndpointCompatibilityTestCase):
    API_ID = "{endpoint['id']}"
    TEST_POINT_IDS = ("{test_point}",)

    def test_{endpoint['id'].lower().replace('-', '_')}_compatibility(self) -> None:
        """{endpoint['module']} / {endpoint['wiring']} / {endpoint['controller_action']} / {test_point}."""
{data_declaration}        result = self.request_both(
            method="{endpoint['method']}",
            path="{endpoint['path']}",
{data_argument}        )
        self.assert_responses_compatible(result)
'''


def main() -> int:
    script = Path(__file__).resolve()
    suite = script.parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=suite / "config" / "endpoints.json")
    parser.add_argument("--fixtures", type=Path, default=suite / "config" / "fixtures.example.json")
    parser.add_argument("--output", type=Path, default=suite / "tests" / "endpoints")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    payload = json.loads(args.manifest.read_text(encoding="utf-8"))
    fixture_config = json.loads(args.fixtures.read_text(encoding="utf-8"))
    endpoints = payload["endpoints"]
    if len(endpoints) != 153:
        raise ValueError(f"expected 153 endpoint entries, found {len(endpoints)}")
    expected = {slug(endpoint): render(endpoint, fixture_config) for endpoint in endpoints}
    if len(expected) != 153:
        raise ValueError("generated endpoint filenames are not unique")
    args.output.mkdir(parents=True, exist_ok=True)
    init = args.output / "__init__.py"
    expected_init = '"""One generated Python test file per confirmed API endpoint."""\n'
    drift: list[str] = []
    if init.exists() and init.read_text(encoding="utf-8") != expected_init:
        drift.append(str(init))
    for name, content in expected.items():
        path = args.output / name
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            drift.append(str(path))
    existing = {path.name for path in args.output.glob("test_api_*.py")}
    stale = sorted(existing - set(expected))
    drift.extend(str(args.output / name) for name in stale)
    if args.check:
        if drift:
            print("endpoint test drift:")
            for path in drift:
                print(path)
            return 1
        print(f"endpoint test files verified: {len(expected)}")
        return 0
    init.write_text(expected_init, encoding="utf-8")
    for name in stale:
        path = args.output / name
        first_line = path.read_text(encoding="utf-8").splitlines()[0] if path.exists() else ""
        if first_line != GENERATED_MARKER:
            raise ValueError(f"refusing to remove non-generated endpoint test: {path}")
        path.unlink()
    for name, content in expected.items():
        (args.output / name).write_text(content, encoding="utf-8")
    print(f"generated {len(expected)} endpoint test files -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
