# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-150 GET /api/v2/fiber/graph_nodes/:node_id/transactions — 节点关联交易."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI150(EndpointCompatibilityTestCase):
    API_ID = "API-150"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_150_compatibility(self) -> None:
        """MOD-FIBER / ACTIVE / api/v2/fiber/graph_nodes#transactions / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/fiber/graph_nodes/:node_id/transactions",
        )
        self.assert_responses_compatible(result)
