# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-093 GET /api/v2/nft/cota/nft_classes/:nft_class_id/tokens/:id/sender — CoTA Token 发送者."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI093(EndpointCompatibilityTestCase):
    API_ID = "API-093"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-003",)

    def test_api_093_compatibility(self) -> None:
        """MOD-NFT-RGB / NAMESPACE_MISMATCH / api/v2/nft/cota/tokens#sender / TP-COMPATIBILITY-API-CONTRACT-003."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/cota/nft_classes/:nft_class_id/tokens/:id/sender",
        )
        self.assert_responses_compatible(result)
