# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-014 GET /api/v2/ckb_transactions — V2 交易列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI014(EndpointCompatibilityTestCase):
    API_ID = "API-014"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_014_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ROUTE_ONLY / api/v2/ckb_transactions#index / TP-COMPATIBILITY-API-CONTRACT-002."""
        result = self.request_both(
            method="GET",
            path="/v2/ckb_transactions",
        )
        self.assert_responses_compatible(result)
