# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-129 GET /api/v1/distribution_data/:id — 分布数据."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI129(EndpointCompatibilityTestCase):
    API_ID = "API-129"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_129_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/distribution_data#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/distribution_data/:id",
        )
        self.assert_responses_compatible(result)
