# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-118 GET /api/v1/suggest_queries — 搜索建议."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI118(EndpointCompatibilityTestCase):
    API_ID = "API-118"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_118_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/suggest_queries#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/suggest_queries",
        )
        self.assert_responses_compatible(result)
