# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-113 GET /api/v2/scripts/ckb_transactions — 脚本关联交易."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI113(EndpointCompatibilityTestCase):
    API_ID = "API-113"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_113_compatibility(self) -> None:
        """MOD-CONTRACT-SCRIPT / ACTIVE / api/v2/scripts#ckb_transactions / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/scripts/ckb_transactions",
        )
        self.assert_responses_compatible(result)
