# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-133 GET /api/v2/statistics/contract_resource_distributed — 合约资源分布."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI133(EndpointCompatibilityTestCase):
    API_ID = "API-133"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_133_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v2/statistics#contract_resource_distributed / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/statistics/contract_resource_distributed",
        )
        self.assert_responses_compatible(result)
