# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-105 GET /api/v2/rgb_live_cells — RGB Live Cells."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI105(EndpointCompatibilityTestCase):
    API_ID = "API-105"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_105_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/rgb_live_cells#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/rgb_live_cells",
        )
        self.assert_responses_compatible(result)
