# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-110 GET /api/v1/contract_transactions/download_csv — 导出合约交易 CSV."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI110(EndpointCompatibilityTestCase):
    API_ID = "API-110"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_110_compatibility(self) -> None:
        """MOD-CONTRACT-SCRIPT / ACTIVE / api/v1/contract_transactions#download_csv / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/contract_transactions/download_csv",
        )
        self.assert_responses_compatible(result)
