# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-091 GET /api/v2/nft/cota/nft_classes/:nft_class_id/tokens — CoTA Token 列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI091(EndpointCompatibilityTestCase):
    API_ID = "API-091"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-003",)

    def test_api_091_compatibility(self) -> None:
        """MOD-NFT-RGB / NAMESPACE_MISMATCH / api/v2/nft/cota/tokens#index / TP-COMPATIBILITY-API-CONTRACT-003."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/cota/nft_classes/:nft_class_id/tokens",
        )
        self.assert_responses_compatible(result)
