# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-136 PUT /api/v2/portfolio/user — 更新 Portfolio 用户."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI136(EndpointCompatibilityTestCase):
    API_ID = "API-136"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_136_compatibility(self) -> None:
        """MOD-PORTFOLIO / ACTIVE / api/v2/portfolio/users#update / TP-COMPATIBILITY-API-CONTRACT-001."""
        data = {'name': 'compatibility-unauthenticated'}

        result = self.request_both(
            method="PUT",
            path="/v2/portfolio/user",
            json_body=data,
        )
        self.assert_responses_compatible(result)
