# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-020 POST /api/v2/transactions — REST 创建交易."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI020(EndpointCompatibilityTestCase):
    API_ID = "API-020"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_020_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ROUTE_ONLY / api/v2/transactions#create / TP-COMPATIBILITY-API-CONTRACT-002."""
        data = {'transaction': {}}

        result = self.request_both(
            method="POST",
            path="/v2/transactions",
            json_body=data,
        )
        self.assert_responses_compatible(result)
