# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-023 GET /api/v2/transactions/:id/edit — REST 编辑交易表单."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI023(EndpointCompatibilityTestCase):
    API_ID = "API-023"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_023_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ROUTE_ONLY / api/v2/transactions#edit / TP-COMPATIBILITY-API-CONTRACT-002."""
        result = self.request_both(
            method="GET",
            path="/v2/transactions/:id/edit",
        )
        self.assert_responses_compatible(result)
