# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-097 GET /api/v2/nft/items — 全局 NFT Item 列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI097(EndpointCompatibilityTestCase):
    API_ID = "API-097"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_097_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/nft/items#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/items",
        )
        self.assert_responses_compatible(result)
