# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-031 GET /api/v2/blocks/ckb_node_versions — CKB 节点版本分布."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI031(EndpointCompatibilityTestCase):
    API_ID = "API-031"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_031_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v2/blocks#ckb_node_versions / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/blocks/ckb_node_versions",
        )
        self.assert_responses_compatible(result)
