# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-034 GET /api/v1/address_dao_transactions/:id — 地址 DAO 交易."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI034(EndpointCompatibilityTestCase):
    API_ID = "API-034"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_034_compatibility(self) -> None:
        """MOD-ADDRESS-DAO / ACTIVE / api/v1/address_dao_transactions#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/address_dao_transactions/:id",
        )
        self.assert_responses_compatible(result)
