# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-102 GET /api/v2/bitcoin_addresses/:id — Bitcoin 地址详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI102(EndpointCompatibilityTestCase):
    API_ID = "API-102"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_102_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/bitcoin_addresses#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/bitcoin_addresses/:id",
        )
        self.assert_responses_compatible(result)
