# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-027 GET /api/v2/transactions/:id/raw — 原始交易结构."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI027(EndpointCompatibilityTestCase):
    API_ID = "API-027"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_027_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v2/transactions#raw / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/transactions/:id/raw",
        )
        self.assert_responses_compatible(result)
