# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-015 GET /api/v2/ckb_transactions/:id — V2 交易详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI015(EndpointCompatibilityTestCase):
    API_ID = "API-015"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_015_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ROUTE_ONLY / api/v2/ckb_transactions#show / TP-COMPATIBILITY-API-CONTRACT-002."""
        result = self.request_both(
            method="GET",
            path="/v2/ckb_transactions/:id",
        )
        self.assert_responses_compatible(result)
