# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-072 GET /api/v2/nft/collections/new — NFT 集合新建表单."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI072(EndpointCompatibilityTestCase):
    API_ID = "API-072"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_072_compatibility(self) -> None:
        """MOD-NFT-RGB / ROUTE_ONLY / api/v2/nft/collections#new / TP-COMPATIBILITY-API-CONTRACT-002."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/collections/new",
        )
        self.assert_responses_compatible(result)
