# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-130 GET /api/v1/monetary_data/:id — 货币数据."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI130(EndpointCompatibilityTestCase):
    API_ID = "API-130"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_130_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/monetary_data#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/monetary_data/:id",
        )
        self.assert_responses_compatible(result)
