# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-099 GET /api/v2/nft/transfers/download_csv — 导出 NFT 转移 CSV."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI099(EndpointCompatibilityTestCase):
    API_ID = "API-099"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_099_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/nft/transfers#download_csv / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/transfers/download_csv",
        )
        self.assert_responses_compatible(result)
