# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-146 GET /api/v2/fiber/graph_nodes — Fiber Graph Node 列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI146(EndpointCompatibilityTestCase):
    API_ID = "API-146"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_146_compatibility(self) -> None:
        """MOD-FIBER / ACTIVE / api/v2/fiber/graph_nodes#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/fiber/graph_nodes",
        )
        self.assert_responses_compatible(result)
