# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-065 GET /api/v2/udt_hourly_statistics — UDT 小时统计列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI065(EndpointCompatibilityTestCase):
    API_ID = "API-065"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_065_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v2/udt_hourly_statistics#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/udt_hourly_statistics",
        )
        self.assert_responses_compatible(result)
