# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-147 GET /api/v2/fiber/graph_nodes/addresses — Fiber Graph Node 地址列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI147(EndpointCompatibilityTestCase):
    API_ID = "API-147"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_147_compatibility(self) -> None:
        """MOD-FIBER / ACTIVE / api/v2/fiber/graph_nodes#addresses / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/fiber/graph_nodes/addresses",
        )
        self.assert_responses_compatible(result)
