# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-103 GET /api/v2/bitcoin_addresses/:id/rgb_cells — Bitcoin 地址 RGB Cells."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI103(EndpointCompatibilityTestCase):
    API_ID = "API-103"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_103_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/bitcoin_addresses#rgb_cells / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/bitcoin_addresses/:id/rgb_cells",
        )
        self.assert_responses_compatible(result)
