# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-100 GET /api/v2/nft/transfers/:id — NFT 转移详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI100(EndpointCompatibilityTestCase):
    API_ID = "API-100"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_100_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/nft/transfers#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/transfers/:id",
        )
        self.assert_responses_compatible(result)
