# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-038 GET /api/v1/dao_depositors — DAO 存款人列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI038(EndpointCompatibilityTestCase):
    API_ID = "API-038"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_038_compatibility(self) -> None:
        """MOD-ADDRESS-DAO / ACTIVE / api/v1/dao_depositors#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/dao_depositors",
        )
        self.assert_responses_compatible(result)
