# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-116 GET /api/v2/scripts/general_info — 脚本通用信息."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI116(EndpointCompatibilityTestCase):
    API_ID = "API-116"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_116_compatibility(self) -> None:
        """MOD-CONTRACT-SCRIPT / ACTIVE / api/v2/scripts#general_info / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/scripts/general_info",
        )
        self.assert_responses_compatible(result)
