# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-134 POST /api/v2/portfolio/sessions — 创建 Portfolio 会话."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI134(EndpointCompatibilityTestCase):
    API_ID = "API-134"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_134_compatibility(self) -> None:
        """MOD-PORTFOLIO / ACTIVE / api/v2/portfolio/sessions#create / TP-COMPATIBILITY-API-CONTRACT-001."""
        data = {'address': 'ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqd39cmf94qpcvcld503al9jf4gs99ky56sunhuuk', 'message': 'compatibility-invalid', 'signature': '0x00', 'pub_key': '0x00'}

        result = self.request_both(
            method="POST",
            path="/v2/portfolio/sessions",
            json_body=data,
        )
        self.assert_responses_compatible(result)
