# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-073 GET /api/v2/nft/collections/:id — NFT 集合详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI073(EndpointCompatibilityTestCase):
    API_ID = "API-073"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_073_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/nft/collections#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/collections/:id",
        )
        self.assert_responses_compatible(result)
