# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-019 GET /api/v2/transactions — REST 交易列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI019(EndpointCompatibilityTestCase):
    API_ID = "API-019"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_019_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ROUTE_ONLY / api/v2/transactions#index / TP-COMPATIBILITY-API-CONTRACT-002."""
        result = self.request_both(
            method="GET",
            path="/v2/transactions",
        )
        self.assert_responses_compatible(result)
