# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-049 PUT /api/v1/udts/:id — 更新 UDT 元数据."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI049(EndpointCompatibilityTestCase):
    API_ID = "API-049"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_049_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/udts#update / TP-COMPATIBILITY-API-CONTRACT-001."""
        data = {'email': ''}

        result = self.request_both(
            method="PUT",
            path="/v1/udts/:id",
            json_body=data,
        )
        self.assert_responses_compatible(result)
