# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-033 GET /api/v1/addresses/:id — 地址详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI033(EndpointCompatibilityTestCase):
    API_ID = "API-033"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_033_compatibility(self) -> None:
        """MOD-ADDRESS-DAO / ACTIVE / api/v1/addresses#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/addresses/:id",
        )
        self.assert_responses_compatible(result)
