# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-126 GET /api/v1/epoch_statistics/:id — Epoch 统计."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI126(EndpointCompatibilityTestCase):
    API_ID = "API-126"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_126_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/epoch_statistics#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/epoch_statistics/:id",
        )
        self.assert_responses_compatible(result)
