# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-001 GET /api/v1/blocks — 区块列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI001(EndpointCompatibilityTestCase):
    API_ID = "API-001"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_001_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v1/blocks#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/blocks",
        )
        self.assert_responses_compatible(result)
