# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-002 GET /api/v1/blocks/download_csv — 导出区块 CSV."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI002(EndpointCompatibilityTestCase):
    API_ID = "API-002"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_002_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v1/blocks#download_csv / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/blocks/download_csv",
        )
        self.assert_responses_compatible(result)
