# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-077 DELETE /api/v2/nft/collections/:id — 删除 NFT 集合."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI077(EndpointCompatibilityTestCase):
    API_ID = "API-077"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_077_compatibility(self) -> None:
        """MOD-NFT-RGB / ROUTE_ONLY / api/v2/nft/collections#destroy / TP-COMPATIBILITY-API-CONTRACT-002."""
        result = self.request_both(
            method="DELETE",
            path="/v2/nft/collections/:id",
        )
        self.assert_responses_compatible(result)
