# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-151 GET /api/v2/fiber/graph_channels — Fiber Graph Channel 列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI151(EndpointCompatibilityTestCase):
    API_ID = "API-151"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_151_compatibility(self) -> None:
        """MOD-FIBER / ACTIVE / api/v2/fiber/graph_channels#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/fiber/graph_channels",
        )
        self.assert_responses_compatible(result)
