# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-016 GET /api/v2/ckb_transactions/:id/details — 交易资产变更明细."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI016(EndpointCompatibilityTestCase):
    API_ID = "API-016"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_016_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v2/ckb_transactions#details / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/ckb_transactions/:id/details",
        )
        self.assert_responses_compatible(result)
