# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-061 GET /api/v1/udt_transactions/:id — UDT 交易列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI061(EndpointCompatibilityTestCase):
    API_ID = "API-061"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_061_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/udt_transactions#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/udt_transactions/:id",
        )
        self.assert_responses_compatible(result)
