# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-088 GET /api/v2/nft/collections/:collection_id/items/:item_id/transfers — NFT Item 转移列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI088(EndpointCompatibilityTestCase):
    API_ID = "API-088"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_088_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/nft/transfers#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/collections/:collection_id/items/:item_id/transfers",
        )
        self.assert_responses_compatible(result)
