# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-095 GET /api/v2/nft/cota/issuers/:id — CoTA Issuer 详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI095(EndpointCompatibilityTestCase):
    API_ID = "API-095"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-003",)

    def test_api_095_compatibility(self) -> None:
        """MOD-NFT-RGB / NAMESPACE_MISMATCH / api/v2/nft/cota/issuers#show / TP-COMPATIBILITY-API-CONTRACT-003."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/cota/issuers/:id",
        )
        self.assert_responses_compatible(result)
