# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-009 GET /api/v1/cell_input_type_scripts/:id — 输入 Cell Type Script."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI009(EndpointCompatibilityTestCase):
    API_ID = "API-009"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_009_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v1/cell_input_type_scripts#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/cell_input_type_scripts/:id",
        )
        self.assert_responses_compatible(result)
