# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-132 GET /api/v2/statistics/transaction_fees — 交易手续费统计."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI132(EndpointCompatibilityTestCase):
    API_ID = "API-132"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_132_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v2/statistics#transaction_fees / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/statistics/transaction_fees",
        )
        self.assert_responses_compatible(result)
