# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-127 GET /api/v1/market_data — 市场数据列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI127(EndpointCompatibilityTestCase):
    API_ID = "API-127"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_127_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/market_data#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/market_data",
        )
        self.assert_responses_compatible(result)
