# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-122 GET /api/v1/nets/:id — 网络信息详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI122(EndpointCompatibilityTestCase):
    API_ID = "API-122"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_122_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/nets#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/nets/:id",
        )
        self.assert_responses_compatible(result)
