# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-037 GET /api/v1/dao_contract_transactions/:id — DAO 合约交易."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI037(EndpointCompatibilityTestCase):
    API_ID = "API-037"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_037_compatibility(self) -> None:
        """MOD-ADDRESS-DAO / ACTIVE / api/v1/dao_contract_transactions#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/dao_contract_transactions/:id",
        )
        self.assert_responses_compatible(result)
