# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-029 GET /api/v2/pending_transactions — 待处理交易列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI029(EndpointCompatibilityTestCase):
    API_ID = "API-029"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_029_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v2/pending_transactions#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/pending_transactions",
        )
        self.assert_responses_compatible(result)
