# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-123 GET /api/v1/statistic_info_charts — 统计图表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI123(EndpointCompatibilityTestCase):
    API_ID = "API-123"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_123_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/statistic_info_charts#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/statistic_info_charts",
        )
        self.assert_responses_compatible(result)
