# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-081 POST /api/v2/nft/collections/:collection_id/items — 创建 NFT Item."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI081(EndpointCompatibilityTestCase):
    API_ID = "API-081"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_081_compatibility(self) -> None:
        """MOD-NFT-RGB / ROUTE_ONLY / api/v2/nft/items#create / TP-COMPATIBILITY-API-CONTRACT-002."""
        data = {'name': 'compatibility-invalid', 'token_id': '0'}

        result = self.request_both(
            method="POST",
            path="/v2/nft/collections/:collection_id/items",
            json_body=data,
        )
        self.assert_responses_compatible(result)
