# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-060 GET /api/v1/omiga_inscriptions/:id — Omiga 铭文详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI060(EndpointCompatibilityTestCase):
    API_ID = "API-060"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_060_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/omiga_inscriptions#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/omiga_inscriptions/:id",
        )
        self.assert_responses_compatible(result)
