# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-087 DELETE /api/v2/nft/collections/:collection_id/items/:id — 删除 NFT Item."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI087(EndpointCompatibilityTestCase):
    API_ID = "API-087"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_087_compatibility(self) -> None:
        """MOD-NFT-RGB / ROUTE_ONLY / api/v2/nft/items#destroy / TP-COMPATIBILITY-API-CONTRACT-002."""
        result = self.request_both(
            method="DELETE",
            path="/v2/nft/collections/:collection_id/items/:id",
        )
        self.assert_responses_compatible(result)
