# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-013 GET /api/v1/cell_output_data/:id — 输出 Cell Data."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI013(EndpointCompatibilityTestCase):
    API_ID = "API-013"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_013_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v1/cell_output_data#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/cell_output_data/:id",
        )
        self.assert_responses_compatible(result)
