# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-059 GET /api/v1/omiga_inscriptions/download_csv — 导出 Omiga 铭文 CSV."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI059(EndpointCompatibilityTestCase):
    API_ID = "API-059"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_059_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/omiga_inscriptions#download_csv / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/omiga_inscriptions/download_csv",
        )
        self.assert_responses_compatible(result)
