# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-112 GET /api/v2/scripts — 脚本列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI112(EndpointCompatibilityTestCase):
    API_ID = "API-112"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_112_compatibility(self) -> None:
        """MOD-CONTRACT-SCRIPT / ACTIVE / api/v2/scripts#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/scripts",
        )
        self.assert_responses_compatible(result)
