# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-104 GET /api/v2/bitcoin_addresses/:id/udt_accounts — Bitcoin 地址 UDT 账户."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI104(EndpointCompatibilityTestCase):
    API_ID = "API-104"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_104_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/bitcoin_addresses#udt_accounts / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/bitcoin_addresses/:id/udt_accounts",
        )
        self.assert_responses_compatible(result)
