# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-149 GET /api/v2/fiber/graph_nodes/:node_id/graph_channels — 节点关联 Channel."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI149(EndpointCompatibilityTestCase):
    API_ID = "API-149"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_149_compatibility(self) -> None:
        """MOD-FIBER / ACTIVE / api/v2/fiber/graph_nodes#graph_channels / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/fiber/graph_nodes/:node_id/graph_channels",
        )
        self.assert_responses_compatible(result)
