# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-140 GET /api/v2/portfolio/ckb_transactions — Portfolio 交易列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI140(EndpointCompatibilityTestCase):
    API_ID = "API-140"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_140_compatibility(self) -> None:
        """MOD-PORTFOLIO / ACTIVE / api/v2/portfolio/ckb_transactions#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/portfolio/ckb_transactions",
        )
        self.assert_responses_compatible(result)
