# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-082 GET /api/v2/nft/collections/:collection_id/items/new — NFT Item 新建表单."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI082(EndpointCompatibilityTestCase):
    API_ID = "API-082"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_082_compatibility(self) -> None:
        """MOD-NFT-RGB / ROUTE_ONLY / api/v2/nft/items#new / TP-COMPATIBILITY-API-CONTRACT-002."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/collections/:collection_id/items/new",
        )
        self.assert_responses_compatible(result)
