# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-084 GET /api/v2/nft/collections/:collection_id/items/:id/edit — NFT Item 编辑表单."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI084(EndpointCompatibilityTestCase):
    API_ID = "API-084"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_084_compatibility(self) -> None:
        """MOD-NFT-RGB / ROUTE_ONLY / api/v2/nft/items#edit / TP-COMPATIBILITY-API-CONTRACT-002."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/collections/:collection_id/items/:id/edit",
        )
        self.assert_responses_compatible(result)
