# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-145 GET /api/v2/fiber/channels/:channel_id — Fiber Channel 详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI145(EndpointCompatibilityTestCase):
    API_ID = "API-145"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_145_compatibility(self) -> None:
        """MOD-FIBER / ACTIVE / api/v2/fiber/channels#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/fiber/channels/:channel_id",
        )
        self.assert_responses_compatible(result)
