# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-005 GET /api/v1/transactions — 交易列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI005(EndpointCompatibilityTestCase):
    API_ID = "API-005"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_005_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v1/ckb_transactions#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/transactions",
        )
        self.assert_responses_compatible(result)
