# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-078 GET /api/v2/nft/collections/:collection_id/holders — NFT 集合持有人."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI078(EndpointCompatibilityTestCase):
    API_ID = "API-078"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_078_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/nft/holders#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/collections/:collection_id/holders",
        )
        self.assert_responses_compatible(result)
