# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-021 GET /api/v2/transactions/new — REST 新建交易表单."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI021(EndpointCompatibilityTestCase):
    API_ID = "API-021"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_021_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ROUTE_ONLY / api/v2/transactions#new / TP-COMPATIBILITY-API-CONTRACT-002."""
        result = self.request_both(
            method="GET",
            path="/v2/transactions/new",
        )
        self.assert_responses_compatible(result)
