# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-101 GET /api/v2/bitcoin_statistics — Bitcoin 统计."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI101(EndpointCompatibilityTestCase):
    API_ID = "API-101"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_101_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/bitcoin_statistics#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/bitcoin_statistics",
        )
        self.assert_responses_compatible(result)
