# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-044 GET /api/v1/udt_queries — UDT 搜索."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI044(EndpointCompatibilityTestCase):
    API_ID = "API-044"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_044_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/udt_queries#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/udt_queries",
        )
        self.assert_responses_compatible(result)
