# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-143 POST /api/v2/fiber/peers — 创建/测试 Fiber Peer 连接."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI143(EndpointCompatibilityTestCase):
    API_ID = "API-143"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_143_compatibility(self) -> None:
        """MOD-FIBER / ACTIVE / api/v2/fiber/peers#create / TP-COMPATIBILITY-API-CONTRACT-001."""
        data = {'name': 'compatibility-invalid', 'peer_id': 'QmCompatibilityFixturePeer', 'rpc_listening_addr': 'http://127.0.0.1:1'}

        result = self.request_both(
            method="POST",
            path="/v2/fiber/peers",
            json_body=data,
        )
        self.assert_responses_compatible(result)
