# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-070 GET /api/v2/nft/collections — NFT 集合列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI070(EndpointCompatibilityTestCase):
    API_ID = "API-070"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_070_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/nft/collections#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/collections",
        )
        self.assert_responses_compatible(result)
