# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-008 GET /api/v1/cell_input_lock_scripts/:id — 输入 Cell Lock Script."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI008(EndpointCompatibilityTestCase):
    API_ID = "API-008"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_008_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v1/cell_input_lock_scripts#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/cell_input_lock_scripts/:id",
        )
        self.assert_responses_compatible(result)
