# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-045 GET /api/v1/udts — UDT 列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI045(EndpointCompatibilityTestCase):
    API_ID = "API-045"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_045_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/udts#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/udts",
        )
        self.assert_responses_compatible(result)
