# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-043 GET /api/v2/dao_events — DAO 事件列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI043(EndpointCompatibilityTestCase):
    API_ID = "API-043"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_043_compatibility(self) -> None:
        """MOD-ADDRESS-DAO / ACTIVE / api/v2/dao_events#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/dao_events",
        )
        self.assert_responses_compatible(result)
