# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-042 GET /api/v1/address_deployed_cells/:id — 地址部署 Cells."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI042(EndpointCompatibilityTestCase):
    API_ID = "API-042"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_042_compatibility(self) -> None:
        """MOD-ADDRESS-DAO / ACTIVE / api/v1/address_deployed_cells#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/address_deployed_cells/:id",
        )
        self.assert_responses_compatible(result)
