# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-022 GET /api/v2/transactions/:id — REST 交易详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI022(EndpointCompatibilityTestCase):
    API_ID = "API-022"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_022_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ROUTE_ONLY / api/v2/transactions#show / TP-COMPATIBILITY-API-CONTRACT-002."""
        result = self.request_both(
            method="GET",
            path="/v2/transactions/:id",
        )
        self.assert_responses_compatible(result)
