# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-066 GET /api/v2/udt_hourly_statistics/:id — UDT 小时统计详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI066(EndpointCompatibilityTestCase):
    API_ID = "API-066"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_066_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v2/udt_hourly_statistics#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/udt_hourly_statistics/:id",
        )
        self.assert_responses_compatible(result)
