# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-057 GET /api/v1/fungible_tokens/:id — 同质化代币详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI057(EndpointCompatibilityTestCase):
    API_ID = "API-057"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_057_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/fungible_tokens#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/fungible_tokens/:id",
        )
        self.assert_responses_compatible(result)
