# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-050 GET /api/v1/udts/:id/holder_allocation — UDT 持仓分布."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI050(EndpointCompatibilityTestCase):
    API_ID = "API-050"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_050_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/udts#holder_allocation / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/udts/:id/holder_allocation",
        )
        self.assert_responses_compatible(result)
