# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-028 GET /api/v2/transactions/:id/details — CKB 容量变更明细."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI028(EndpointCompatibilityTestCase):
    API_ID = "API-028"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_028_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v2/transactions#details / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/transactions/:id/details",
        )
        self.assert_responses_compatible(result)
