# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-035 GET /api/v1/address_transactions/:id — 地址交易列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI035(EndpointCompatibilityTestCase):
    API_ID = "API-035"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_035_compatibility(self) -> None:
        """MOD-ADDRESS-DAO / ACTIVE / api/v1/address_transactions#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/address_transactions/:id",
        )
        self.assert_responses_compatible(result)
