# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-152 GET /api/v2/fiber/statistics — Fiber 统计列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI152(EndpointCompatibilityTestCase):
    API_ID = "API-152"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_152_compatibility(self) -> None:
        """MOD-FIBER / ACTIVE / api/v2/fiber/statistics#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/fiber/statistics",
        )
        self.assert_responses_compatible(result)
