# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-017 GET /api/v2/ckb_transactions/:id/display_inputs — 分页展示交易输入."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI017(EndpointCompatibilityTestCase):
    API_ID = "API-017"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_017_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v2/ckb_transactions#display_inputs / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/ckb_transactions/:id/display_inputs",
        )
        self.assert_responses_compatible(result)
