# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-055 GET /api/v1/fungible_tokens — 同质化代币列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI055(EndpointCompatibilityTestCase):
    API_ID = "API-055"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_055_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/fungible_tokens#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/fungible_tokens",
        )
        self.assert_responses_compatible(result)
