# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-079 GET /api/v2/nft/collections/:collection_id/transfers — NFT 集合转移记录."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI079(EndpointCompatibilityTestCase):
    API_ID = "API-079"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_079_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/nft/transfers#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/collections/:collection_id/transfers",
        )
        self.assert_responses_compatible(result)
