# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-131 GET /api/v2/monitors/daily_statistics — 监控每日统计."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI131(EndpointCompatibilityTestCase):
    API_ID = "API-131"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_131_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v2/monitors/daily_statistics#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/monitors/daily_statistics",
        )
        self.assert_responses_compatible(result)
