# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-090 GET /api/v2/nft/cota/nft_classes — CoTA NFT Class 列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI090(EndpointCompatibilityTestCase):
    API_ID = "API-090"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-003",)

    def test_api_090_compatibility(self) -> None:
        """MOD-NFT-RGB / NAMESPACE_MISMATCH / api/v2/nft/cota/nft_classes#index / TP-COMPATIBILITY-API-CONTRACT-003."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/cota/nft_classes",
        )
        self.assert_responses_compatible(result)
