# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-092 GET /api/v2/nft/cota/nft_classes/:nft_class_id/tokens/:id/claimed — CoTA Token 领取状态."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI092(EndpointCompatibilityTestCase):
    API_ID = "API-092"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-003",)

    def test_api_092_compatibility(self) -> None:
        """MOD-NFT-RGB / NAMESPACE_MISMATCH / api/v2/nft/cota/tokens#claimed / TP-COMPATIBILITY-API-CONTRACT-003."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/cota/nft_classes/:nft_class_id/tokens/:id/claimed",
        )
        self.assert_responses_compatible(result)
