# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-010 GET /api/v1/cell_input_data/:id — 输入 Cell Data."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI010(EndpointCompatibilityTestCase):
    API_ID = "API-010"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_010_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v1/cell_input_data#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/cell_input_data/:id",
        )
        self.assert_responses_compatible(result)
