# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-030 GET /api/v2/pending_transactions/count — 待处理交易数量."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI030(EndpointCompatibilityTestCase):
    API_ID = "API-030"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_030_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v2/pending_transactions#count / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/pending_transactions/count",
        )
        self.assert_responses_compatible(result)
