# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-011 GET /api/v1/cell_output_lock_scripts/:id — 输出 Cell Lock Script."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI011(EndpointCompatibilityTestCase):
    API_ID = "API-011"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_011_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v1/cell_output_lock_scripts#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/cell_output_lock_scripts/:id",
        )
        self.assert_responses_compatible(result)
