# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-141 GET /api/v2/portfolio/ckb_transactions/download_csv — 导出 Portfolio 交易 CSV."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI141(EndpointCompatibilityTestCase):
    API_ID = "API-141"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_141_compatibility(self) -> None:
        """MOD-PORTFOLIO / ACTIVE / api/v2/portfolio/ckb_transactions#download_csv / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/portfolio/ckb_transactions/download_csv",
        )
        self.assert_responses_compatible(result)
