# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-144 GET /api/v2/fiber/peers/:peer_id — Fiber Peer 详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI144(EndpointCompatibilityTestCase):
    API_ID = "API-144"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_144_compatibility(self) -> None:
        """MOD-FIBER / ACTIVE / api/v2/fiber/peers#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/fiber/peers/:peer_id",
        )
        self.assert_responses_compatible(result)
