# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-069 GET /api/v2/ckb_transactions/:id/rgb_digest — RGB++ 交易摘要."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI069(EndpointCompatibilityTestCase):
    API_ID = "API-069"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_069_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/ckb_transactions#rgb_digest / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/ckb_transactions/:id/rgb_digest",
        )
        self.assert_responses_compatible(result)
