# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-142 GET /api/v2/fiber/peers — Fiber Peer 列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI142(EndpointCompatibilityTestCase):
    API_ID = "API-142"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_142_compatibility(self) -> None:
        """MOD-FIBER / ACTIVE / api/v2/fiber/peers#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/fiber/peers",
        )
        self.assert_responses_compatible(result)
