# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-047 GET /api/v1/udts/:id — UDT 详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI047(EndpointCompatibilityTestCase):
    API_ID = "API-047"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_047_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/udts#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/udts/:id",
        )
        self.assert_responses_compatible(result)
