# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-111 GET /api/v1/contracts/:id — 合约详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI111(EndpointCompatibilityTestCase):
    API_ID = "API-111"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_111_compatibility(self) -> None:
        """MOD-CONTRACT-SCRIPT / ACTIVE / api/v1/contracts#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/contracts/:id",
        )
        self.assert_responses_compatible(result)
