# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-067 POST /api/v2/das_accounts — DAS 账户查询."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI067(EndpointCompatibilityTestCase):
    API_ID = "API-067"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_067_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/das_accounts#query / TP-COMPATIBILITY-API-CONTRACT-001."""
        data = {'addresses': ['ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqd39cmf94qpcvcld503al9jf4gs99ky56sunhuuk']}

        result = self.request_both(
            method="POST",
            path="/v2/das_accounts",
            json_body=data,
        )
        self.assert_responses_compatible(result)
