# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-096 GET /api/v2/nft/cota/issuers/:id/minted — CoTA Issuer 铸造记录."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI096(EndpointCompatibilityTestCase):
    API_ID = "API-096"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-003",)

    def test_api_096_compatibility(self) -> None:
        """MOD-NFT-RGB / NAMESPACE_MISMATCH / api/v2/nft/cota/issuers#minted / TP-COMPATIBILITY-API-CONTRACT-003."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/cota/issuers/:id/minted",
        )
        self.assert_responses_compatible(result)
