# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-138 POST /api/v2/portfolio/addresses — 添加 Portfolio 地址."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI138(EndpointCompatibilityTestCase):
    API_ID = "API-138"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_138_compatibility(self) -> None:
        """MOD-PORTFOLIO / ACTIVE / api/v2/portfolio/addresses#create / TP-COMPATIBILITY-API-CONTRACT-001."""
        data = {'addresses': ['ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqd39cmf94qpcvcld503al9jf4gs99ky56sunhuuk']}

        result = self.request_both(
            method="POST",
            path="/v2/portfolio/addresses",
            json_body=data,
        )
        self.assert_responses_compatible(result)
