# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-098 GET /api/v2/nft/transfers — 全局 NFT 转移列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI098(EndpointCompatibilityTestCase):
    API_ID = "API-098"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_098_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/nft/transfers#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/transfers",
        )
        self.assert_responses_compatible(result)
