# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-006 GET /api/v1/transactions/:id — 交易详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI006(EndpointCompatibilityTestCase):
    API_ID = "API-006"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_006_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v1/ckb_transactions#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/transactions/:id",
        )
        self.assert_responses_compatible(result)
