# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-124 GET /api/v1/daily_statistics/:id — 每日统计."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI124(EndpointCompatibilityTestCase):
    API_ID = "API-124"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_124_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/daily_statistics#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/daily_statistics/:id",
        )
        self.assert_responses_compatible(result)
