# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-094 GET /api/v2/nft/cota/transactions — CoTA 交易列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI094(EndpointCompatibilityTestCase):
    API_ID = "API-094"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-003",)

    def test_api_094_compatibility(self) -> None:
        """MOD-NFT-RGB / NAMESPACE_MISMATCH / api/v2/nft/cota/transactions#index / TP-COMPATIBILITY-API-CONTRACT-003."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/cota/transactions",
        )
        self.assert_responses_compatible(result)
