# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-018 GET /api/v2/ckb_transactions/:id/display_outputs — 分页展示交易输出."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI018(EndpointCompatibilityTestCase):
    API_ID = "API-018"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_018_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v2/ckb_transactions#display_outputs / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/ckb_transactions/:id/display_outputs",
        )
        self.assert_responses_compatible(result)
