# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-074 GET /api/v2/nft/collections/:id/edit — NFT 集合编辑表单."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI074(EndpointCompatibilityTestCase):
    API_ID = "API-074"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_074_compatibility(self) -> None:
        """MOD-NFT-RGB / ROUTE_ONLY / api/v2/nft/collections#edit / TP-COMPATIBILITY-API-CONTRACT-002."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/collections/:id/edit",
        )
        self.assert_responses_compatible(result)
