# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-139 GET /api/v2/portfolio/udt_accounts — Portfolio UDT 账户."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI139(EndpointCompatibilityTestCase):
    API_ID = "API-139"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_139_compatibility(self) -> None:
        """MOD-PORTFOLIO / ACTIVE / api/v2/portfolio/udt_accounts#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/portfolio/udt_accounts",
        )
        self.assert_responses_compatible(result)
