# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-040 GET /api/v1/address_pending_transactions/:id — 地址待处理交易."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI040(EndpointCompatibilityTestCase):
    API_ID = "API-040"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_040_compatibility(self) -> None:
        """MOD-ADDRESS-DAO / ACTIVE / api/v1/address_pending_transactions#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/address_pending_transactions/:id",
        )
        self.assert_responses_compatible(result)
