# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-089 GET /api/v2/nft/collections/:collection_id/items/:item_id/transfers/:id — NFT Item 转移详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI089(EndpointCompatibilityTestCase):
    API_ID = "API-089"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_089_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/nft/transfers#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/collections/:collection_id/items/:item_id/transfers/:id",
        )
        self.assert_responses_compatible(result)
