# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-086 PUT /api/v2/nft/collections/:collection_id/items/:id — 更新 NFT Item."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI086(EndpointCompatibilityTestCase):
    API_ID = "API-086"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_086_compatibility(self) -> None:
        """MOD-NFT-RGB / ROUTE_ONLY / api/v2/nft/items#update / TP-COMPATIBILITY-API-CONTRACT-002."""
        data = {'name': 'compatibility-invalid', 'token_id': '0'}

        result = self.request_both(
            method="PUT",
            path="/v2/nft/collections/:collection_id/items/:id",
            json_body=data,
        )
        self.assert_responses_compatible(result)
