# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-003 GET /api/v1/blocks/:id — 区块详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI003(EndpointCompatibilityTestCase):
    API_ID = "API-003"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_003_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v1/blocks#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/blocks/:id",
        )
        self.assert_responses_compatible(result)
