# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-051 GET /api/v1/xudts — xUDT 列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI051(EndpointCompatibilityTestCase):
    API_ID = "API-051"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_051_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/xudts#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/xudts",
        )
        self.assert_responses_compatible(result)
