# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-062 GET /api/v1/address_udt_transactions/:id — 地址 UDT 交易."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI062(EndpointCompatibilityTestCase):
    API_ID = "API-062"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_062_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/address_udt_transactions#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/address_udt_transactions/:id",
        )
        self.assert_responses_compatible(result)
