# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-063 PATCH /api/v1/udt_verifications/:id — 更新 UDT 验证."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI063(EndpointCompatibilityTestCase):
    API_ID = "API-063"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_063_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/udt_verifications#update / TP-COMPATIBILITY-API-CONTRACT-001."""
        data = {'locale': 'en'}

        result = self.request_both(
            method="PATCH",
            path="/v1/udt_verifications/:id",
            json_body=data,
        )
        self.assert_responses_compatible(result)
