# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-083 GET /api/v2/nft/collections/:collection_id/items/:id — NFT Item 详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI083(EndpointCompatibilityTestCase):
    API_ID = "API-083"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_083_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/nft/items#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/collections/:collection_id/items/:id",
        )
        self.assert_responses_compatible(result)
