# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-053 GET /api/v1/xudts/snapshot — xUDT 快照."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI053(EndpointCompatibilityTestCase):
    API_ID = "API-053"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_053_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/xudts#snapshot / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/xudts/snapshot",
        )
        self.assert_responses_compatible(result)
