# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-153 GET /api/v2/fiber/statistics/:id — Fiber 统计详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI153(EndpointCompatibilityTestCase):
    API_ID = "API-153"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_153_compatibility(self) -> None:
        """MOD-FIBER / ACTIVE / api/v2/fiber/statistics#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/fiber/statistics/:id",
        )
        self.assert_responses_compatible(result)
