# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-054 GET /api/v1/xudts/:id — xUDT 详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI054(EndpointCompatibilityTestCase):
    API_ID = "API-054"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_054_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/xudts#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/xudts/:id",
        )
        self.assert_responses_compatible(result)
