# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-058 GET /api/v1/omiga_inscriptions — Omiga 铭文列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI058(EndpointCompatibilityTestCase):
    API_ID = "API-058"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_058_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/omiga_inscriptions#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/omiga_inscriptions",
        )
        self.assert_responses_compatible(result)
