# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-071 POST /api/v2/nft/collections — 创建 NFT 集合."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI071(EndpointCompatibilityTestCase):
    API_ID = "API-071"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_071_compatibility(self) -> None:
        """MOD-NFT-RGB / ROUTE_ONLY / api/v2/nft/collections#create / TP-COMPATIBILITY-API-CONTRACT-002."""
        data = {'name': 'compatibility-invalid'}

        result = self.request_both(
            method="POST",
            path="/v2/nft/collections",
            json_body=data,
        )
        self.assert_responses_compatible(result)
