# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-137 GET /api/v2/portfolio/statistics — Portfolio 统计."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI137(EndpointCompatibilityTestCase):
    API_ID = "API-137"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_137_compatibility(self) -> None:
        """MOD-PORTFOLIO / ACTIVE / api/v2/portfolio/statistics#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/portfolio/statistics",
        )
        self.assert_responses_compatible(result)
