# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-121 GET /api/v1/nets — 网络信息列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI121(EndpointCompatibilityTestCase):
    API_ID = "API-121"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_121_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/nets#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/nets",
        )
        self.assert_responses_compatible(result)
