# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-046 GET /api/v1/udts/download_csv — 导出 UDT CSV."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI046(EndpointCompatibilityTestCase):
    API_ID = "API-046"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_046_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/udts#download_csv / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/udts/download_csv",
        )
        self.assert_responses_compatible(result)
