# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-036 GET /api/v1/address_transactions/download_csv — 导出地址交易 CSV."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI036(EndpointCompatibilityTestCase):
    API_ID = "API-036"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_036_compatibility(self) -> None:
        """MOD-ADDRESS-DAO / ACTIVE / api/v1/address_transactions#download_csv / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/address_transactions/download_csv",
        )
        self.assert_responses_compatible(result)
