# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-108 GET /api/v2/rgb_top_holders/:id — RGB Top Holders."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI108(EndpointCompatibilityTestCase):
    API_ID = "API-108"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_108_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/rgb_top_holders#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/rgb_top_holders/:id",
        )
        self.assert_responses_compatible(result)
