# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-107 GET /api/v2/rgb_assets_statistics — RGB 资产统计."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI107(EndpointCompatibilityTestCase):
    API_ID = "API-107"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_107_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/rgb_assets_statistics#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/rgb_assets_statistics",
        )
        self.assert_responses_compatible(result)
