# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-056 GET /api/v1/fungible_tokens/download_csv — 导出同质化代币 CSV."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI056(EndpointCompatibilityTestCase):
    API_ID = "API-056"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_056_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/fungible_tokens#download_csv / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/fungible_tokens/download_csv",
        )
        self.assert_responses_compatible(result)
