# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-120 GET /api/v1/statistics/:id — 统计详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI120(EndpointCompatibilityTestCase):
    API_ID = "API-120"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_120_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/statistics#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/statistics/:id",
        )
        self.assert_responses_compatible(result)
