# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-068 POST /api/v2/bitcoin_transactions — Bitcoin 交易查询."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI068(EndpointCompatibilityTestCase):
    API_ID = "API-068"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_068_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/bitcoin_transactions#query / TP-COMPATIBILITY-API-CONTRACT-001."""
        data = {'txids': []}

        result = self.request_both(
            method="POST",
            path="/v2/bitcoin_transactions",
            json_body=data,
        )
        self.assert_responses_compatible(result)
