# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-039 GET /api/v1/dao_depositors/download_csv — 导出 DAO 存款人 CSV."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI039(EndpointCompatibilityTestCase):
    API_ID = "API-039"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_039_compatibility(self) -> None:
        """MOD-ADDRESS-DAO / ACTIVE / api/v1/dao_depositors#download_csv / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/dao_depositors/download_csv",
        )
        self.assert_responses_compatible(result)
