# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-128 GET /api/v1/market_data/:id — 市场数据详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI128(EndpointCompatibilityTestCase):
    API_ID = "API-128"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_128_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/market_data#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/market_data/:id",
        )
        self.assert_responses_compatible(result)
