# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-115 GET /api/v2/scripts/referring_cells — 脚本引用 Cells."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI115(EndpointCompatibilityTestCase):
    API_ID = "API-115"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_115_compatibility(self) -> None:
        """MOD-CONTRACT-SCRIPT / ACTIVE / api/v2/scripts#referring_cells / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/scripts/referring_cells",
        )
        self.assert_responses_compatible(result)
