# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-148 GET /api/v2/fiber/graph_nodes/:node_id — Fiber Graph Node 详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI148(EndpointCompatibilityTestCase):
    API_ID = "API-148"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_148_compatibility(self) -> None:
        """MOD-FIBER / ACTIVE / api/v2/fiber/graph_nodes#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/fiber/graph_nodes/:node_id",
        )
        self.assert_responses_compatible(result)
