# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-125 GET /api/v1/block_statistics/:id — 区块统计（源码标注 unused）."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI125(EndpointCompatibilityTestCase):
    API_ID = "API-125"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_125_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/block_statistics#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/block_statistics/:id",
        )
        self.assert_responses_compatible(result)
