# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-052 GET /api/v1/xudts/download_csv — 导出 xUDT CSV."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI052(EndpointCompatibilityTestCase):
    API_ID = "API-052"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_052_compatibility(self) -> None:
        """MOD-TOKENS / ACTIVE / api/v1/xudts#download_csv / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/xudts/download_csv",
        )
        self.assert_responses_compatible(result)
