# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-004 GET /api/v1/block_transactions/:id — 区块交易列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI004(EndpointCompatibilityTestCase):
    API_ID = "API-004"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_004_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v1/block_transactions#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/block_transactions/:id",
        )
        self.assert_responses_compatible(result)
