# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-026 DELETE /api/v2/transactions/:id — REST 删除交易."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI026(EndpointCompatibilityTestCase):
    API_ID = "API-026"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_026_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ROUTE_ONLY / api/v2/transactions#destroy / TP-COMPATIBILITY-API-CONTRACT-002."""
        result = self.request_both(
            method="DELETE",
            path="/v2/transactions/:id",
        )
        self.assert_responses_compatible(result)
