# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-080 GET /api/v2/nft/collections/:collection_id/items — 集合 NFT Item 列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI080(EndpointCompatibilityTestCase):
    API_ID = "API-080"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_080_compatibility(self) -> None:
        """MOD-NFT-RGB / ACTIVE / api/v2/nft/items#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/nft/collections/:collection_id/items",
        )
        self.assert_responses_compatible(result)
