# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-109 GET /api/v1/contract_transactions/:id — 合约交易列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI109(EndpointCompatibilityTestCase):
    API_ID = "API-109"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_109_compatibility(self) -> None:
        """MOD-CONTRACT-SCRIPT / ACTIVE / api/v1/contract_transactions#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/contract_transactions/:id",
        )
        self.assert_responses_compatible(result)
