# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-007 POST /api/v1/transactions/query — 批量/条件查询交易."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI007(EndpointCompatibilityTestCase):
    API_ID = "API-007"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_007_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v1/ckb_transactions#query / TP-COMPATIBILITY-API-CONTRACT-001."""
        data = {'page': 1, 'page_size': 2}

        result = self.request_both(
            method="POST",
            path="/v1/transactions/query",
            json_body=data,
        )
        self.assert_responses_compatible(result)
