# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-117 GET /api/v1/external/stats/:id — 外部统计详情."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI117(EndpointCompatibilityTestCase):
    API_ID = "API-117"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_117_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/external/stats#show / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/external/stats/:id",
        )
        self.assert_responses_compatible(result)
