# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-119 GET /api/v1/statistics — 统计列表."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI119(EndpointCompatibilityTestCase):
    API_ID = "API-119"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_119_compatibility(self) -> None:
        """MOD-STATISTICS-DISCOVERY / ACTIVE / api/v1/statistics#index / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v1/statistics",
        )
        self.assert_responses_compatible(result)
