# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-032 GET /api/v2/blocks/by_epoch — 按 Epoch 查询区块."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI032(EndpointCompatibilityTestCase):
    API_ID = "API-032"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_032_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ACTIVE / api/v2/blocks#by_epoch / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/blocks/by_epoch",
        )
        self.assert_responses_compatible(result)
