# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-075 PATCH /api/v2/nft/collections/:id — 更新 NFT 集合."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI075(EndpointCompatibilityTestCase):
    API_ID = "API-075"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_075_compatibility(self) -> None:
        """MOD-NFT-RGB / ROUTE_ONLY / api/v2/nft/collections#update / TP-COMPATIBILITY-API-CONTRACT-002."""
        data = {'name': 'compatibility-invalid'}

        result = self.request_both(
            method="PATCH",
            path="/v2/nft/collections/:id",
            json_body=data,
        )
        self.assert_responses_compatible(result)
