# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-024 PATCH /api/v2/transactions/:id — REST 更新交易."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI024(EndpointCompatibilityTestCase):
    API_ID = "API-024"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-002",)

    def test_api_024_compatibility(self) -> None:
        """MOD-CHAIN-DATA / ROUTE_ONLY / api/v2/transactions#update / TP-COMPATIBILITY-API-CONTRACT-002."""
        data = {'transaction': {}}

        result = self.request_both(
            method="PATCH",
            path="/v2/transactions/:id",
            json_body=data,
        )
        self.assert_responses_compatible(result)
