# Generated by scripts/generate_endpoint_tests.py; do not merge API files.
"""API-114 GET /api/v2/scripts/deployed_cells — 脚本部署 Cells."""

from tests.endpoint_support import EndpointCompatibilityTestCase


class TestAPI114(EndpointCompatibilityTestCase):
    API_ID = "API-114"
    TEST_POINT_IDS = ("TP-COMPATIBILITY-API-CONTRACT-001",)

    def test_api_114_compatibility(self) -> None:
        """MOD-CONTRACT-SCRIPT / ACTIVE / api/v2/scripts#deployed_cells / TP-COMPATIBILITY-API-CONTRACT-001."""
        result = self.request_both(
            method="GET",
            path="/v2/scripts/deployed_cells",
        )
        self.assert_responses_compatible(result)
